# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Temp\SAINT_Medical_AI.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        # 프로그램 제목, 위치 출력
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1058, 617)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")

        # Tab 구성
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(10, 10, 831, 561))
        self.tabWidget.setObjectName("tabWidget")
        # 각 tab에 위치할 위젯 생성
        self.tab1 = QtWidgets.QWidget()
        self.tab2 = QtWidgets.QWidget()
        self.tab3 = QtWidgets.QWidget()
        # 각 tab이름 생성
        self.tab1.setObjectName("tab_1")
        self.tab2.setObjectName("tab_2")
        self.tab3.setObjectName("tab_3")
        # 탭 위젯 넣기
        self.tabWidget.addTab(self.tab1, "")
        self.tabWidget.addTab(self.tab2, "")
        self.tabWidget.addTab(self.tab3, "")
        # 수직 layout 3개 생성
        self.tab1_layout = QtWidgets.QVBoxLayout()
        self.tab2_layout = QtWidgets.QVBoxLayout()
        self.tab3_layout = QtWidgets.QVBoxLayout()
        # 수직 layout을 위젯의 레이아웃으로 설정
        self.tab1.setLayout(self.tab1_layout)
        self.tab2.setLayout(self.tab2_layout)
        self.tab3.setLayout(self.tab3_layout)
        # tabl에 넣을 이미지 라벨 생성
        self.tab1_label = QtWidgets.QLabel()
        self.tab2_label = QtWidgets.QLabel()
        self.tab3_label = QtWidgets.QLabel()
        # 라벨 배치
        self.tab1_layout.addWidget(self.tab1_label, alignment=QtCore.Qt.AlignCenter)
        self.tab2_layout.addWidget(self.tab2_label, alignment=QtCore.Qt.AlignCenter)
        self.tab3_layout.addWidget(self.tab3_label, alignment=QtCore.Qt.AlignCenter)

        # MenuBar 구성
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1058, 21))
        self.menubar.setObjectName("menubar")
        self.File = QtWidgets.QMenu(self.menubar)
        self.File.setObjectName("File")
        self.Edit = QtWidgets.QMenu(self.menubar)
        self.Edit.setObjectName("Edit")
        self.View = QtWidgets.QMenu(self.menubar)
        self.View.setObjectName("View")
        self.menuTools = QtWidgets.QMenu(self.menubar)
        self.menuTools.setObjectName("menuTools")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")

        # 왼쪽 하단부 시간, 날짜 표시
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        self.date = QtCore.QDate.currentDate()
        self.statusbar.showMessage(self.date.toString(QtCore.Qt.DefaultLocaleLongDate))

        # MenuBar 액션 설정
        MainWindow.setStatusBar(self.statusbar)
        self.actionFile_Open = QtWidgets.QAction(MainWindow)
        self.actionFile_Open.triggered.connect(self.openImage)
        self.actionFile_Open.setObjectName("actionFile_Open")
        self.actionExit = QtWidgets.QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.File.addAction(self.actionFile_Open)
        self.File.addAction(self.actionExit)
        self.menubar.addAction(self.File.menuAction())
        self.menubar.addAction(self.Edit.menuAction())
        self.menubar.addAction(self.View.menuAction())
        self.menubar.addAction(self.menuTools.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    # 원본이미지 불러오기
    def openImage(self):
        imagePath, _ = QtWidgets.QFileDialog.getOpenFileName()
        self.pixmap = QtGui.QPixmap(imagePath)
        #self.pixmap = self.pixmap.scaled(800, 500)
        self.tab1_label.setPixmap(self.pixmap)

    # 크롭이미지 불러오기
    def CropImage(self):
        pass

    # 히트맵 불러오기
    def HeatMap(self):
        pass

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab1), _translate("MainWindow", "Original_img"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab2), _translate("MainWindow", "Crop_img"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab3), _translate("MainWindow", "HeatMap_img"))
        self.File.setTitle(_translate("MainWindow", "File"))
        self.Edit.setTitle(_translate("MainWindow", "Edit"))
        self.View.setTitle(_translate("MainWindow", "View"))
        self.menuTools.setTitle(_translate("MainWindow", "Tools"))
        self.menuHelp.setTitle(_translate("MainWindow", "Help"))
        self.actionFile_Open.setText(_translate("MainWindow", "File Open"))
        self.actionExit.setText(_translate("MainWindow", "Exit"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
